language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
  # pin dep version until its v1 is released
  - DEP_VERSION="0.4.1"

before_install:
  # no deb package yet, install from its github release drop:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - ./test-with-coverage.sh

after_success:
  # upload test coverage results to codecov.io:
  - bash <(curl -s https://codecov.io/bash)
