language: go

os:
  - linux
  - osx

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
  # pin dep version until its v1 is released
  - DEP_RELEASE_PATH="https://github.com/golang/dep/releases/download/v0.4.1"

matrix:
  exclude:
    # limit macOS builds to latest go version (macOS is dev platform, uses latest go)
    - os: osx
      go: 1.8.x
    - os: osx
      go: 1.9.x

before_install:
  # dep is still pre-release, install pinned version from its github release drop:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -L -s "$DEP_RELEASE_PATH/dep-linux-amd64" -o $GOPATH/bin/dep;
      chmod +x $GOPATH/bin/dep;
    fi
  # can't install via curl for macOS, so no pinning on mac
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install dep; fi

install:
  - dep ensure

script:
  - make validate
  - scripts/test-with-coverage.sh

after_success:
  # upload test coverage results to codecov.io:
  - bash <(curl -s https://codecov.io/bash)
